name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Certifique-se de que esta é a sua branch principal no GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Permissão para escrever no repositório
      pages: write # Permissão para gerenciar o GitHub Pages
      id-token: write # Necessário para autenticação com OIDC

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a versão do Node.js que você está usando no seu projeto

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Instalar dependências
        run: pnpm install

      - name: Construir o projeto
        run: pnpm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Certifique-se de que esta é a pasta onde o seu build é gerado

      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
