name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Certifique-se de que este é o seu branch principal no GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: node ./node_modules/vite/bin/vite.js build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # CNAME: example.com # Descomente e configure se você usa um domínio personalizado
